repo: 'responsive-banner'
canvasCourse: 'web-dev-4'

inherit:
  - naming-restrict-live
  - git-2
  - html
  - css
  - css-order-modules-grid-type-main
  - gridifier
  - modulifier
  - typografier
  - screenshots-all
  - modulifier-buttons

html:
  - path: 'index.html'
    has:
      - 'div'
      - 'img.img-flex'
      - 'a.btn.btn-ghost'
      - '.grid-middle'
      - '.wrapper'
    search:
      - 'The Planet Earth'
      - 'An amazingly species rich'
      - 'Book a star cruise'

css:
  - path: 'css/main.css'
    has:
      - ['html', 'font-family', 'Georgia, serif']
    search:
      - '#fff'
      - '#efefef'
      - '#97a49b'
      - '#495562'
      - 'rgba\(73, 85, 98'
      - 'max-height: 500px'
      - 'background-image: linear-gradient'
